spring:
  application:
    name: notification-service
  config:
    import: "aws-secretsmanager:banking/production"
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8085

account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info